<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class CitizenAuthController extends Controller
{
    /**
     * Show citizen registration form
     */
    public function showRegistrationForm()
    {
        return view('citizen.auth.register');
    }

    /**
     * Handle citizen registration
     */
    public function register(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required|string|max:255',
            'middle_name' => 'nullable|string|max:255',
            'last_name' => 'required|string|max:255',
            'name' => 'nullable|string|max:500', // Auto-generated from name components
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'phone_number' => 'required|string|max:20',
            'region' => 'required|string|max:100',
            'city' => 'required|string|max:100',
            'barangay' => 'required|string|max:100',
            'street_address' => 'required|string|max:255',
            'address' => 'required|string|max:500', // This will be auto-generated from the components
            'date_of_birth' => 'required|date|before:today',
            'id_type' => 'required|in:Government-Issued ID,School ID,Driver\'s License,Passport,Senior Citizen ID,PWD ID,Voter\'s ID',
            'id_number' => 'required|string|max:50',
        ]);

        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $user = User::create([
            'first_name' => $request->first_name,
            'middle_name' => $request->middle_name,
            'last_name' => $request->last_name,
            'name' => $request->name, // Auto-generated by JavaScript
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role' => 'citizen',
            'phone_number' => $request->phone_number,
            'region' => $request->region,
            'city' => $request->city,
            'barangay' => $request->barangay,
            'street_address' => $request->street_address,
            'address' => $request->address,
            'date_of_birth' => $request->date_of_birth,
            'id_type' => $request->id_type,
            'id_number' => $request->id_number,
            'is_verified' => false,
        ]);

        Auth::login($user);

        return redirect()->route('citizen.dashboard')->with('success', 'Registration successful! Welcome to the Citizen Portal.');
    }

    /**
     * Show login form (admin or citizen context)
     */
    public function showLoginForm(Request $request)
    {
        // Check if this is admin login based on route or URL
        $isAdminLogin = str_contains($request->url(), '/admin') || $request->route()->getName() === 'admin.login';
        
        if ($isAdminLogin) {
            return view('citizen.auth.login', ['isAdminLogin' => true]);
        }
        
        return view('citizen.auth.login', ['isAdminLogin' => false]);
    }

    /**
     * Handle authentication for both citizen and admin
     */
    public function login(Request $request)
    {
        $credentials = $request->validate([
            'email' => 'required|email',
            'password' => 'required',
        ]);

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            $user = Auth::user();
            
            // Check current route to determine where to redirect
            $currentRoute = $request->route()->getName();
            
            if ($currentRoute === 'admin.login.submit' || str_contains($request->url(), '/admin')) {
                // Admin login attempt
                if ($user->isAdmin()) {
                    return redirect()->intended('/admin/facilities');
                } else {
                    Auth::logout();
                    return back()->withErrors([
                        'email' => 'Access denied. Admin credentials required for administrative access.',
                    ]);
                }
            } else {
                // Citizen login attempt
                if ($user->isCitizen()) {
                    return redirect()->intended('citizen/dashboard');
                } elseif ($user->isAdmin()) {
                    // Admin trying to access citizen portal - redirect to admin
                    return redirect()->route('admin.login')->with('info', 'Redirected to admin portal.');
                }
            }
        }

        return back()->withErrors([
            'email' => 'The provided credentials do not match our records.',
        ]);
    }

    /**
     * Handle logout for both admin and citizen users
     */
    public function logout(Request $request)
    {
        $user = Auth::user();
        $isAdmin = $user && $user->isAdmin();
        
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        // Redirect based on user role
        if ($isAdmin) {
            return redirect()->route('admin.login')->with('success', 'You have been logged out successfully.');
        } else {
            return redirect()->route('citizen.login')->with('success', 'You have been logged out successfully.');
        }
    }
}